import { Category, Product, Testimonial } from "./types";

export const DEMO_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Vêtements", name_ht: "Rad", slug: "vetements", icon: "👗", color: "#F4A7BB", sort_order: 1 },
  { id: "cat-2", name: "Chaussures", name_ht: "Soulye", slug: "chaussures", icon: "👟", color: "#A7D1F4", sort_order: 2 },
  { id: "cat-3", name: "Accessoires", name_ht: "Akseswa", slug: "accessoires", icon: "🎀", color: "#C4B1D4", sort_order: 3 },
  { id: "cat-4", name: "Soins", name_ht: "Swen", slug: "soins", icon: "🧴", color: "#A7F4D1", sort_order: 4 },
  { id: "cat-5", name: "Jouets", name_ht: "Jwèt", slug: "jouets", icon: "🧸", color: "#F4D7A7", sort_order: 5 },
  { id: "cat-6", name: "Literie", name_ht: "Dra kabann", slug: "literie", icon: "🛏️", color: "#D4A7F4", sort_order: 6 },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "prod-1", name: "Ensemble Layette Rose", name_ht: "Ansanm Layèt Woz",
    description: "Ensemble layette 3 pièces en coton bio ultra-doux. Body, pantalon et bonnet assortis. Idéal pour les premiers jours de bébé.",
    description_ht: "Ansanm layèt 3 moso an koton bio ki byen dou. Kò, pantalon ak bonè ki mache. Ideyal pou premye jou tibebe a.",
    price: 2500, old_price: 3200, category_id: "cat-1", gender: "fille", age_range: "0-3",
    colors: ["Rose", "Blanc"], sizes: ["NB", "0-3M"], badge: "new",
    is_featured: true, is_coup_coeur: true, stock: 5, is_active: true, views: 142,
    images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"],
    created_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "prod-2", name: "Barboteuse Bleu Ciel", name_ht: "Babotez Ble Syèl",
    description: "Barboteuse légère en coton, parfaite pour le climat haïtien. Boutons-pression pour un change facile.",
    description_ht: "Babotez lejè an koton, pafè pou klima ayisyen. Bouton presyon pou chanje fasil.",
    price: 1800, old_price: null, category_id: "cat-1", gender: "garcon", age_range: "0-3",
    colors: ["Bleu", "Blanc"], sizes: ["NB", "0-3M"], badge: "popular",
    is_featured: true, is_coup_coeur: false, stock: 12, is_active: true, views: 98,
    images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"],
    created_at: "2026-03-28T00:00:00Z",
  },
  {
    id: "prod-3", name: "Chaussons Tricotés", name_ht: "Ti Soulye Trikote",
    description: "Chaussons faits main au crochet. Doux et confortables pour les petits pieds.",
    description_ht: "Ti soulye fèt ak men ak kwochè. Dou e konfòtab pou ti pye yo.",
    price: 800, old_price: null, category_id: "cat-2", gender: "unisexe", age_range: "0-3",
    colors: ["Blanc", "Rose", "Bleu"], sizes: ["NB", "0-3M"], badge: null,
    is_featured: false, is_coup_coeur: true, stock: 20, is_active: true, views: 67,
    images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"],
    created_at: "2026-03-25T00:00:00Z",
  },
  {
    id: "prod-4", name: "Coffret Soin Nouveau-né", name_ht: "Bwat Swen Nouvo-ne",
    description: "Coffret complet de soins pour bébé : huile, crème, savon doux, brosse à cheveux et coupe-ongles.",
    description_ht: "Bwat konplè swen pou tibebe: lwil, krèm, savon dou, bwòs cheve ak koupe zong.",
    price: 3500, old_price: 4000, category_id: "cat-4", gender: "unisexe", age_range: "0-3",
    colors: [], sizes: [], badge: "new",
    is_featured: true, is_coup_coeur: true, stock: 8, is_active: true, views: 203,
    images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"],
    created_at: "2026-04-05T00:00:00Z",
  },
  {
    id: "prod-5", name: "Peluche Éléphant", name_ht: "Peluch Elefan",
    description: "Peluche éléphant douce et hypoallergénique. Compagnon parfait pour les siestes.",
    description_ht: "Peluch elefan dou e ipoalèjenik. Bon zanmi pou lè dòmi.",
    price: 1500, old_price: null, category_id: "cat-5", gender: "unisexe", age_range: "0-3",
    colors: ["Gris", "Rose"], sizes: [], badge: null,
    is_featured: true, is_coup_coeur: false, stock: 15, is_active: true, views: 89,
    images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"],
    created_at: "2026-03-20T00:00:00Z",
  },
  {
    id: "prod-6", name: "Parure de Lit Étoiles", name_ht: "Dra Kabann Zetwal",
    description: "Parure de lit 4 pièces motif étoiles. Drap-housse, couverture, tour de lit et taie d'oreiller.",
    description_ht: "Dra kabann 4 moso ak motif zetwal. Dra, kouvèti, tou kabann ak tè zorye.",
    price: 4500, old_price: null, category_id: "cat-6", gender: "unisexe", age_range: "0-3",
    colors: ["Blanc", "Jaune"], sizes: [], badge: "limited",
    is_featured: false, is_coup_coeur: false, stock: 3, is_active: true, views: 54,
    images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"],
    created_at: "2026-03-15T00:00:00Z",
  },
  {
    id: "prod-7", name: "Robe Baptême Dentelle", name_ht: "Wòb Batèm Dantèl",
    description: "Robe de baptême élégante en dentelle fine. Livrée avec bandeau assorti.",
    description_ht: "Wòb batèm elegan an dantèl fen. Livré ak bandè ki mache.",
    price: 5500, old_price: 6500, category_id: "cat-1", gender: "fille", age_range: "3-6",
    colors: ["Blanc", "Ivoire"], sizes: ["3-6M"], badge: "popular",
    is_featured: true, is_coup_coeur: true, stock: 4, is_active: true, views: 312,
    images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"],
    created_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "prod-8", name: "Bandeau Fleuri", name_ht: "Bandè Fleri",
    description: "Bandeau élastique doux avec fleur en tissu. Plusieurs couleurs disponibles.",
    description_ht: "Bandè elastik dou ak flè an twal. Plizyè koulè disponib.",
    price: 600, old_price: null, category_id: "cat-3", gender: "fille", age_range: "0-3",
    colors: ["Rose", "Lavande", "Blanc"], sizes: [], badge: null,
    is_featured: false, is_coup_coeur: false, stock: 30, is_active: true, views: 45,
    images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"],
    created_at: "2026-03-08T00:00:00Z",
  },
  {
    id: "prod-9", name: "Costume Garçon Chic", name_ht: "Kostim Ti Gason Chik",
    description: "Ensemble chemise et pantalon pour les occasions spéciales. Tissu confortable et élégant.",
    description_ht: "Ansanm chemiz ak pantalon pou okazyon espesyal. Twal konfòtab e elegan.",
    price: 3800, old_price: null, category_id: "cat-1", gender: "garcon", age_range: "6-12",
    colors: ["Bleu marine", "Gris"], sizes: ["6-12M"], badge: "new",
    is_featured: false, is_coup_coeur: false, stock: 7, is_active: true, views: 33,
    images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"],
    created_at: "2026-04-08T00:00:00Z",
  },
  {
    id: "prod-10", name: "Hochet Musical", name_ht: "Ochè Mizikal",
    description: "Hochet musical en bois naturel non toxique. Stimule l'éveil sensoriel de bébé.",
    description_ht: "Ochè mizikal an bwa natirèl ki pa toksik. Stimile evèy sansoryal tibebe.",
    price: 950, old_price: null, category_id: "cat-5", gender: "unisexe", age_range: "3-6",
    colors: ["Multicolore"], sizes: [], badge: null,
    is_featured: true, is_coup_coeur: false, stock: 18, is_active: true, views: 76,
    images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"],
    created_at: "2026-03-18T00:00:00Z",
  },
  {
    id: "prod-11", name: "Lot de Bavoirs", name_ht: "Pakèt Bavwa",
    description: "Lot de 5 bavoirs en coton absorbant. Motifs variés et attaches velcro.",
    description_ht: "Pakèt 5 bavwa an koton ki absòban. Motif varye ak atach velkwo.",
    price: 1200, old_price: null, category_id: "cat-3", gender: "unisexe", age_range: "0-3",
    colors: ["Assortis"], sizes: [], badge: null,
    is_featured: false, is_coup_coeur: false, stock: 25, is_active: true, views: 41,
    images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"],
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "prod-12", name: "Sandales Souples", name_ht: "Sandal Soup",
    description: "Sandales à semelle souple pour premiers pas. Cuir synthétique de qualité.",
    description_ht: "Sandal ak semèl soup pou premye pa. Kwi sentetik bon kalite.",
    price: 1100, old_price: null, category_id: "cat-2", gender: "fille", age_range: "6-12",
    colors: ["Rose", "Doré"], sizes: ["6-12M"], badge: "new",
    is_featured: false, is_coup_coeur: false, stock: 10, is_active: true, views: 28,
    images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"],
    created_at: "2026-04-03T00:00:00Z",
  },
];

export const DEMO_TESTIMONIALS: Testimonial[] = [
  { id: "test-1", name: "Marie-Claire J.", text_fr: "J'ai trouvé tout ce dont j'avais besoin pour mon bébé au même endroit ! La qualité est excellente.", text_ht: "Mwen jwenn tout sa m te bezwen pou tibebe m nan yon sèl kote! Kalite pwodui yo ekselan.", rating: 5, is_active: true },
  { id: "test-2", name: "Stéphanie P.", text_fr: "Le service est rapide et professionnel. Je recommande Ti Bijou à toutes les mamans !", text_ht: "Sèvis la rapid e pwofesyonèl. M rekòmande Ti Bijou bay tout manman!", rating: 5, is_active: true },
  { id: "test-3", name: "Jocelyne D.", text_fr: "La robe de baptême de ma fille était tellement belle ! Tout le monde l'a adorée.", text_ht: "Wòb batèm pitit fi m nan te tèlman bèl! Tout moun te renmen l.", rating: 5, is_active: true },
];

export const FAQ_DATA = [
  { q_fr: "Comment commander ?", q_ht: "Kijan pou m kòmande?", a_fr: "Cliquez sur le produit qui vous intéresse puis sur \"Je suis intéressé(e)\" — vous pourrez nous écrire sur WhatsApp ou remplir le formulaire.", a_ht: "Klike sou pwodui ki enterese w la, epi klike \"M enterese\" — w ap kapab ekri nou sou WhatsApp oswa ranpli fòmilè a." },
  { q_fr: "Quels sont les délais de livraison ?", q_ht: "Ki delè livrezon?", a_fr: "À Port-au-Prince : 1-2 jours. En province : 3-5 jours.", a_ht: "Nan Pòtoprens: 1-2 jou. Nan pwovens: 3-5 jou." },
  { q_fr: "Quels modes de paiement acceptez-vous ?", q_ht: "Ki mòd pèman nou aksepte?", a_fr: "Nous acceptons : Cash à la livraison, MonCash, Natcash, virement bancaire.", a_ht: "Nou aksepte: Kash nan livrezon, MonCash, Natcash, transfè bankè." },
  { q_fr: "Puis-je retourner un article ?", q_ht: "Èske m ka retounen yon atik?", a_fr: "Oui, dans les 48h après livraison si l'article est en bon état et dans son emballage d'origine.", a_ht: "Wi, nan 48è aprè livrezon si atik la nan bon eta e nan anbalaj orijinal li." },
  { q_fr: "Livrez-vous en province ?", q_ht: "Èske nou livre nan pwovens?", a_fr: "Oui ! Nous livrons partout en Haïti via nos partenaires de transport.", a_ht: "Wi! Nou livre toupatou nan Ayiti ak patnè transpò nou yo." },
];
