import { Category, Product, Testimonial } from "./types";
export const DEMO_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Vêtements", name_ht: "Rad", slug: "vetements", icon: "👗", color: "#F4A7BB", sort_order: 1 },
  { id: "cat-2", name: "Chaussures", name_ht: "Soulye", slug: "chaussures", icon: "👟", color: "#A7D1F4", sort_order: 2 },
  { id: "cat-3", name: "Accessoires", name_ht: "Akseswa", slug: "accessoires", icon: "🎀", color: "#C4B1D4", sort_order: 3 },
  { id: "cat-4", name: "Soins", name_ht: "Swen", slug: "soins", icon: "🧴", color: "#A7F4D1", sort_order: 4 },
  { id: "cat-5", name: "Jouets", name_ht: "Jwèt", slug: "jouets", icon: "🧸", color: "#F4D7A7", sort_order: 5 },
  { id: "cat-6", name: "Literie", name_ht: "Dra kabann", slug: "literie", icon: "🛏️", color: "#D4A7F4", sort_order: 6 },
];
export const DEMO_PRODUCTS: Product[] = [
  { id: "prod-1", name: "Ensemble Layette Rose", name_ht: "Ansanm Layèt Woz", description: "Ensemble layette 3 pièces en coton bio ultra-doux. Body, pantalon et bonnet assortis.", description_ht: "Ansanm layèt 3 moso an koton bio ki byen dou.", price: 2500, old_price: 3200, category_id: "cat-1", gender: "fille", age_range: "0-3", colors: ["Rose","Blanc"], sizes: ["NB","0-3M"], badge: "new", is_featured: true, is_coup_coeur: true, stock: 5, is_active: true, views: 142, images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"], created_at: "2026-04-01T00:00:00Z" },
  { id: "prod-2", name: "Barboteuse Bleu Ciel", name_ht: "Babotez Ble Syèl", description: "Barboteuse légère en coton, parfaite pour le climat haïtien.", description_ht: "Babotez lejè an koton, pafè pou klima ayisyen.", price: 1800, old_price: null, category_id: "cat-1", gender: "garcon", age_range: "0-3", colors: ["Bleu","Blanc"], sizes: ["NB","0-3M"], badge: "popular", is_featured: true, is_coup_coeur: false, stock: 12, is_active: true, views: 98, images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"], created_at: "2026-03-28T00:00:00Z" },
  { id: "prod-3", name: "Chaussons Tricotés", name_ht: "Ti Soulye Trikote", description: "Chaussons faits main au crochet.", description_ht: "Ti soulye fèt ak men ak kwochè.", price: 800, old_price: null, category_id: "cat-2", gender: "unisexe", age_range: "0-3", colors: ["Blanc","Rose","Bleu"], sizes: ["NB","0-3M"], badge: null, is_featured: false, is_coup_coeur: true, stock: 20, is_active: true, views: 67, images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"], created_at: "2026-03-25T00:00:00Z" },
  { id: "prod-4", name: "Coffret Soin Nouveau-né", name_ht: "Bwat Swen Nouvo-ne", description: "Coffret complet : huile, crème, savon, brosse et coupe-ongles.", description_ht: "Bwat konplè swen pou tibebe.", price: 3500, old_price: 4000, category_id: "cat-4", gender: "unisexe", age_range: "0-3", colors: [], sizes: [], badge: "new", is_featured: true, is_coup_coeur: true, stock: 8, is_active: true, views: 203, images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"], created_at: "2026-04-05T00:00:00Z" },
  { id: "prod-5", name: "Peluche Éléphant", name_ht: "Peluch Elefan", description: "Peluche douce et hypoallergénique.", description_ht: "Peluch dou e ipoalèjenik.", price: 1500, old_price: null, category_id: "cat-5", gender: "unisexe", age_range: "0-3", colors: ["Gris","Rose"], sizes: [], badge: null, is_featured: true, is_coup_coeur: false, stock: 15, is_active: true, views: 89, images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"], created_at: "2026-03-20T00:00:00Z" },
  { id: "prod-6", name: "Parure de Lit Étoiles", name_ht: "Dra Kabann Zetwal", description: "Parure 4 pièces motif étoiles.", description_ht: "Dra kabann 4 moso ak motif zetwal.", price: 4500, old_price: null, category_id: "cat-6", gender: "unisexe", age_range: "0-3", colors: ["Blanc","Jaune"], sizes: [], badge: "limited", is_featured: false, is_coup_coeur: false, stock: 3, is_active: true, views: 54, images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"], created_at: "2026-03-15T00:00:00Z" },
  { id: "prod-7", name: "Robe Baptême Dentelle", name_ht: "Wòb Batèm Dantèl", description: "Robe élégante en dentelle fine avec bandeau.", description_ht: "Wòb elegan an dantèl fen ak bandè.", price: 5500, old_price: 6500, category_id: "cat-1", gender: "fille", age_range: "3-6", colors: ["Blanc","Ivoire"], sizes: ["3-6M"], badge: "popular", is_featured: true, is_coup_coeur: true, stock: 4, is_active: true, views: 312, images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"], created_at: "2026-03-10T00:00:00Z" },
  { id: "prod-8", name: "Bandeau Fleuri", name_ht: "Bandè Fleri", description: "Bandeau élastique doux avec fleur en tissu.", description_ht: "Bandè elastik dou ak flè an twal.", price: 600, old_price: null, category_id: "cat-3", gender: "fille", age_range: "0-3", colors: ["Rose","Lavande","Blanc"], sizes: [], badge: null, is_featured: false, is_coup_coeur: false, stock: 30, is_active: true, views: 45, images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"], created_at: "2026-03-08T00:00:00Z" },
  { id: "prod-9", name: "Costume Garçon Chic", name_ht: "Kostim Ti Gason Chik", description: "Ensemble chemise et pantalon pour occasions spéciales.", description_ht: "Ansanm chemiz ak pantalon pou okazyon espesyal.", price: 3800, old_price: null, category_id: "cat-1", gender: "garcon", age_range: "6-12", colors: ["Bleu marine","Gris"], sizes: ["6-12M"], badge: "new", is_featured: false, is_coup_coeur: false, stock: 7, is_active: true, views: 33, images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"], created_at: "2026-04-08T00:00:00Z" },
  { id: "prod-10", name: "Hochet Musical", name_ht: "Ochè Mizikal", description: "Hochet en bois naturel non toxique.", description_ht: "Ochè an bwa natirèl ki pa toksik.", price: 950, old_price: null, category_id: "cat-5", gender: "unisexe", age_range: "3-6", colors: ["Multicolore"], sizes: [], badge: null, is_featured: true, is_coup_coeur: false, stock: 18, is_active: true, views: 76, images: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&h=400&fit=crop"], created_at: "2026-03-18T00:00:00Z" },
  { id: "prod-11", name: "Lot de Bavoirs", name_ht: "Pakèt Bavwa", description: "Lot de 5 bavoirs en coton absorbant.", description_ht: "Pakèt 5 bavwa an koton ki absòban.", price: 1200, old_price: null, category_id: "cat-3", gender: "unisexe", age_range: "0-3", colors: ["Assortis"], sizes: [], badge: null, is_featured: false, is_coup_coeur: false, stock: 25, is_active: true, views: 41, images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&h=400&fit=crop"], created_at: "2026-03-05T00:00:00Z" },
  { id: "prod-12", name: "Sandales Souples", name_ht: "Sandal Soup", description: "Sandales à semelle souple pour premiers pas.", description_ht: "Sandal ak semèl soup pou premye pa.", price: 1100, old_price: null, category_id: "cat-2", gender: "fille", age_range: "6-12", colors: ["Rose","Doré"], sizes: ["6-12M"], badge: "new", is_featured: false, is_coup_coeur: false, stock: 10, is_active: true, views: 28, images: ["https://images.unsplash.com/photo-1519689680058-324335c77eba?w=400&h=400&fit=crop"], created_at: "2026-04-03T00:00:00Z" },
];
export const DEMO_TESTIMONIALS: Testimonial[] = [
  { id: "t1", name: "Marie-Claire J.", text_fr: "J'ai trouvé tout ce dont j'avais besoin pour mon bébé ! Qualité excellente.", text_ht: "Mwen jwenn tout sa m te bezwen pou tibebe m! Kalite ekselan.", rating: 5, is_active: true },
  { id: "t2", name: "Stéphanie P.", text_fr: "Service rapide et professionnel. Je recommande Ti Bijou !", text_ht: "Sèvis rapid e pwofesyonèl. M rekòmande Ti Bijou!", rating: 5, is_active: true },
  { id: "t3", name: "Jocelyne D.", text_fr: "La robe de baptême de ma fille était magnifique !", text_ht: "Wòb batèm pitit fi m nan te tèlman bèl!", rating: 5, is_active: true },
];
export const FAQ_DATA = [
  { q_fr: "Comment commander ?", q_ht: "Kijan pou m kòmande?", a_fr: "Cliquez sur le produit puis \"Je suis intéressé(e)\" — WhatsApp ou formulaire.", a_ht: "Klike sou pwodui a epi \"M enterese\" — WhatsApp oswa fòmilè." },
  { q_fr: "Délais de livraison ?", q_ht: "Ki delè livrezon?", a_fr: "Port-au-Prince: 1-2 jours. Province: 3-5 jours.", a_ht: "Pòtoprens: 1-2 jou. Pwovens: 3-5 jou." },
  { q_fr: "Modes de paiement ?", q_ht: "Ki mòd pèman?", a_fr: "Cash à la livraison, MonCash, Natcash, virement.", a_ht: "Kash nan livrezon, MonCash, Natcash, transfè." },
  { q_fr: "Retours possibles ?", q_ht: "Èske m ka retounen?", a_fr: "Oui, dans les 48h si article en bon état.", a_ht: "Wi, nan 48è si atik la an bon eta." },
  { q_fr: "Livraison en province ?", q_ht: "Livre nan pwovens?", a_fr: "Oui, partout en Haïti !", a_ht: "Wi, toupatou nan Ayiti!" },
];
